#!/bin/sh
prefix=D:/bld/pdal_1599683721292/_h_env/Library
exec_prefix=D:/bld/pdal_1599683721292/_h_env/Library/bin
libdir=D:/bld/pdal_1599683721292/_h_env/Library/lib

usage()
{
	cat <<EOF
Usage: pdal-config [OPTIONS]
Options:
	[--cflags]
	[--cxxflags]
	[--defines]
	[--includes]
	[--libs]
	[--plugin-dir]
	[--version]
EOF
	exit $1
}

if test $# -eq 0; then
	usage 1 1>&2
fi

case $1 in
  --libs)
    echo -LD:/bld/pdal_1599683721292/_h_env/Library/lib -lpdalcpp
    ;;

  --plugin-dir)
    echo D:/bld/pdal_1599683721292/_h_env/Library/bin
    ;;

  --prefix)
    echo ${prefix}
     ;;

  --ldflags)
    echo -L${libdir}
    ;;

  --defines)
    echo 
    ;;

  --includes)
    echo -ID:/bld/pdal_1599683721292/_h_env/Library/include -ID:/bld/pdal_1599683721292/_h_env/Library/include -ID:/bld/pdal_1599683721292/_h_env/Library/include -ID:/bld/pdal_1599683721292/_h_env/Library/include
    ;;

  --cflags)
    echo /DWIN32 /D_WINDOWS /W3
    ;;

  --cxxflags)
    echo /DWIN32 /D_WINDOWS /W3 /GR /EHsc -std=c++11
    ;;

  --version)
    echo 2.2.0
    ;;

  *)
    usage 1 1>&2
    ;;

esac
