### YamlMime:ManagedReference
items:
- uid: Project
  commentId: N:Project
  id: Project
  children:
  - Project.GeographyCollection
  - Project.GeographyCollection.GeogData
  - Project.GeologyCollection
  - Project.GeologyCollection.GeoData
  - Project.GeoTypes
  - Project.GisProject
  - Project.JsonTransform
  - Project.RecordSet
  - Project.RecordsetConverter
  - Project.RecordSetDataType
  - Project.RecordSetType
  - Project.Serializable
  - Project.SerializableColor
  - Project.SerializableQuaternion
  - Project.SerializableVector3
  - Project.Shapes
  - Project.TestableObject
  - Project.Unit
  - Project.VectorConverter`1
  langs:
  - csharp
  - vb
  name: Project
  nameWithType: Project
  fullName: Project
  type: Namespace
  assemblies:
  - Assembly-CSharp
references:
- uid: Project.GisProject
  commentId: T:Project.GisProject
  parent: Project
  name: GisProject
  nameWithType: GisProject
  fullName: Project.GisProject
- uid: Project.RecordSet
  commentId: T:Project.RecordSet
  parent: Project
  name: RecordSet
  nameWithType: RecordSet
  fullName: Project.RecordSet
- uid: Project.JsonTransform
  commentId: T:Project.JsonTransform
  parent: Project
  name: JsonTransform
  nameWithType: JsonTransform
  fullName: Project.JsonTransform
- uid: Project.VectorConverter`1
  commentId: T:Project.VectorConverter`1
  name: VectorConverter<T>
  nameWithType: VectorConverter<T>
  fullName: Project.VectorConverter<T>
  nameWithType.vb: VectorConverter(Of T)
  fullName.vb: Project.VectorConverter(Of T)
  name.vb: VectorConverter(Of T)
  spec.csharp:
  - uid: Project.VectorConverter`1
    name: VectorConverter
    nameWithType: VectorConverter
    fullName: Project.VectorConverter
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Project.VectorConverter`1
    name: VectorConverter
    nameWithType: VectorConverter
    fullName: Project.VectorConverter
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Project.RecordsetConverter
  commentId: T:Project.RecordsetConverter
  parent: Project
  name: RecordsetConverter
  nameWithType: RecordsetConverter
  fullName: Project.RecordsetConverter
- uid: Project.RecordSetType
  commentId: T:Project.RecordSetType
  parent: Project
  name: RecordSetType
  nameWithType: RecordSetType
  fullName: Project.RecordSetType
- uid: Project.GeographyCollection
  commentId: T:Project.GeographyCollection
  parent: Project
  name: GeographyCollection
  nameWithType: GeographyCollection
  fullName: Project.GeographyCollection
- uid: Project.GeographyCollection.GeogData
  commentId: T:Project.GeographyCollection.GeogData
  parent: Project
  name: GeographyCollection.GeogData
  nameWithType: GeographyCollection.GeogData
  fullName: Project.GeographyCollection.GeogData
- uid: Project.GeologyCollection
  commentId: T:Project.GeologyCollection
  name: GeologyCollection
  nameWithType: GeologyCollection
  fullName: Project.GeologyCollection
- uid: Project.GeologyCollection.GeoData
  commentId: T:Project.GeologyCollection.GeoData
  parent: Project
  name: GeologyCollection.GeoData
  nameWithType: GeologyCollection.GeoData
  fullName: Project.GeologyCollection.GeoData
- uid: Project.RecordSetDataType
  commentId: T:Project.RecordSetDataType
  parent: Project
  name: RecordSetDataType
  nameWithType: RecordSetDataType
  fullName: Project.RecordSetDataType
- uid: Project.GeoTypes
  commentId: T:Project.GeoTypes
  parent: Project
  name: GeoTypes
  nameWithType: GeoTypes
  fullName: Project.GeoTypes
- uid: Project.Unit
  commentId: T:Project.Unit
  name: Unit
  nameWithType: Unit
  fullName: Project.Unit
- uid: Project.Shapes
  commentId: T:Project.Shapes
  parent: Project
  name: Shapes
  nameWithType: Shapes
  fullName: Project.Shapes
- uid: Project.TestableObject
  commentId: T:Project.TestableObject
  parent: Project
  name: TestableObject
  nameWithType: TestableObject
  fullName: Project.TestableObject
- uid: Project.SerializableVector3
  commentId: T:Project.SerializableVector3
  parent: Project
  name: SerializableVector3
  nameWithType: SerializableVector3
  fullName: Project.SerializableVector3
- uid: Project.SerializableQuaternion
  commentId: T:Project.SerializableQuaternion
  parent: Project
  name: SerializableQuaternion
  nameWithType: SerializableQuaternion
  fullName: Project.SerializableQuaternion
- uid: Project.SerializableColor
  commentId: T:Project.SerializableColor
  parent: Project
  name: SerializableColor
  nameWithType: SerializableColor
  fullName: Project.SerializableColor
- uid: Project.Serializable
  commentId: T:Project.Serializable
  parent: Project
  name: Serializable
  nameWithType: Serializable
  fullName: Project.Serializable
- uid: Project
  commentId: N:Project
  name: Project
  nameWithType: Project
  fullName: Project
