apiRules:
- include:
    uidRegex: ^Virgis
    type: Namespace
- include:
    uidRegex: ^Project
    type: Namespace
- include:
    uidRegex: ^g3
    type: Namespace
- include:
    uidRegex: ^GeoJSON.Net
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace