name: Create Documentation
on: workflow_dispatch

jobs:
  documentation:
    runs-on: ubuntu-latest
    name: generate docs
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: dir
      run: |
        pwd
        ls -alR
    
    - uses: nikeee/docfx-action@v1
      name: Build Documentation
      with:
        args: Documentation/docfx.json
