name: Create Documentation
on: workflow_dispatch

jobs:
  documentation:
    runs-on: windows-latest
    name: generate docs
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install DocFX
      run: choco install -y docfx

    - name: Build
      run: |
        docfx Documentation/docfx.json

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update Documentation" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
